#
io.army.example.stock.domain.StockChatVectorStore.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779290105916}
io.army.example.stock.domain.StockChatVectorStore.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.example.stock.domain.StockChatVectorStore.embedding.Column.precision=1024
io.army.example.stock.domain.StockChatVectorStore.conversationId.Mapping.value=io.army.mapping.SqlBigIntType
#
io.army.example.stock.domain.StockDocumentVectorStore.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779290105918}
io.army.example.stock.domain.StockDocumentVectorStore.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.example.stock.domain.StockDocumentVectorStore.embedding.Column.precision=1024
#
io.army.example.stock.domain.StockChatMemory.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779103273327}
io.army.example.stock.domain.StockChatMemory.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.example.stock.domain.StockChatMemory.conversationId.Mapping.value=io.army.mapping.SqlBigIntType
#




