#
io.army.spring.ai.vectorstore.SpringAiVectorStore.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779290105916}
io.army.spring.ai.vectorstore.SpringAiVectorStore.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.spring.ai.vectorstore.SpringAiVectorStore.Table.name=stock_vector_store
io.army.spring.ai.vectorstore.SpringAiVectorStore.embedding.Column.precision=1024
io.army.spring.ai.vectorstore.SpringAiVectorStore.IndexMeta[0].type=hnsw
io.army.spring.ai.vectorstore.SpringAiVectorStore.IndexMeta[0].field.embedding.opclass=vector_l2_ops
#
#
io.army.spring.ai.chat.memory.SpringAiChatMemory.Table.name=stock_chat_memory
io.army.spring.ai.chat.memory.SpringAiChatMemory.Table.ddlMode=true
io.army.spring.ai.chat.memory.SpringAiChatMemory.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779103273327}
io.army.spring.ai.chat.memory.SpringAiChatMemory.batchNo.Column.name=batch_no
io.army.spring.ai.chat.memory.SpringAiChatMemory.userId.Mapping.value=io.army.mapping.SqlBigIntType
io.army.spring.ai.chat.memory.SpringAiChatMemory.userId.Column.defaultValue=0
io.army.spring.ai.chat.memory.SpringAiChatMemory.conversationId.Mapping.value=io.army.mapping.SqlBigIntType
#
#
io.army.spring.ai.chat.memory.SpringAiChatConversation.Table.name=stock_chat_conversation
io.army.spring.ai.chat.memory.SpringAiChatConversation.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.spring.ai.chat.memory.SpringAiChatConversation.userId.Mapping.value=io.army.mapping.SqlBigIntType


