/*
 * Copyright 2023-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.army.dialect;

import io.army.sqltype.MySQLType;
import io.army.util._Collections;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public abstract class _MySQLDialectUtils {

    static final Map<String, MySQLType> ALIAS_TO_TYPE_MAP = Map.copyOf(createAliasToTypeMap());

    private _MySQLDialectUtils() {
        throw new UnsupportedOperationException();
    }

    public static Map<String, MySQLType> getAliasToTypeMap() {
        return ALIAS_TO_TYPE_MAP;
    }


    /// @return a modifiable set
    /// @see <a href="https://dev.mysql.com/doc/refman/8.2/en/keywords.html">Keywords and Reserved Words</a>
    static Set<String> create57KeywordsSet() {
        Set<String> set = new HashSet<>();

        set.add("ACCESSIBLE");
        set.add("ACCOUNT");
        set.add("ACTION");
        set.add("ADD");
        set.add("AFTER");
        set.add("AGAINST");
        set.add("AGGREGATE");
        set.add("ALGORITHM");
        set.add("ALL");
        set.add("ALTER");
        set.add("ALWAYS");
        set.add("ANALYSE");
        set.add("ANALYZE");
        set.add("AND");
        set.add("ANY");
        set.add("AS");
        set.add("ASC");
        set.add("ASCII");
        set.add("ASENSITIVE");
        set.add("AT");
        set.add("AUTOEXTEND_SIZE");
        set.add("AUTO_INCREMENT");
        set.add("AVG");
        set.add("AVG_ROW_LENGTH");
        set.add("BACKUP");
        set.add("BEFORE");
        set.add("BEGIN");
        set.add("BETWEEN");
        set.add("BIGINT");
        set.add("BINARY");
        set.add("BINLOG");
        set.add("BIT");
        set.add("BLOB");
        set.add("BLOCK");
        set.add("BOOL");
        set.add("BOOLEAN");
        set.add("BOTH");
        set.add("BTREE");
        set.add("BY");
        set.add("BYTE");
        set.add("CACHE");
        set.add("CALL");
        set.add("CASCADE");
        set.add("CASCADED");
        set.add("CASE");
        set.add("CATALOG_NAME");
        set.add("CHAIN");
        set.add("CHANGE");
        set.add("CHANGED");
        set.add("CHANNEL");
        set.add("CHAR");
        set.add("CHARACTER");
        set.add("CHARSET");
        set.add("CHECK");
        set.add("CHECKSUM");
        set.add("CIPHER");
        set.add("CLASS_ORIGIN");
        set.add("CLIENT");
        set.add("CLOSE");
        set.add("COALESCE");
        set.add("CODE");
        set.add("COLLATE");
        set.add("COLLATION");
        set.add("COLUMN");
        set.add("COLUMNS");
        set.add("COLUMN_FORMAT");
        set.add("COLUMN_NAME");
        set.add("COMMENT");
        set.add("COMMIT");
        set.add("COMMITTED");
        set.add("COMPACT");
        set.add("COMPLETION");
        set.add("COMPRESSED");
        set.add("COMPRESSION");
        set.add("CONCURRENT");
        set.add("CONDITION");
        set.add("CONNECTION");
        set.add("CONSISTENT");
        set.add("CONSTRAINT");
        set.add("CONSTRAINT_CATALOG");
        set.add("CONSTRAINT_NAME");
        set.add("CONSTRAINT_SCHEMA");
        set.add("CONTAINS");
        set.add("CONTEXT");
        set.add("CONTINUE");
        set.add("CONVERT");
        set.add("CPU");
        set.add("CREATE");
        set.add("CROSS");
        set.add("CUBE");
        set.add("CURRENT");
        set.add("CURRENT_DATE");
        set.add("CURRENT_TIME");
        set.add("CURRENT_TIMESTAMP");
        set.add("CURRENT_USER");
        set.add("CURSOR");
        set.add("CURSOR_NAME");
        set.add("DATA");
        set.add("DATABASE");
        set.add("DATABASES");
        set.add("DATAFILE");
        set.add("DATE");
        set.add("DATETIME");
        set.add("DAY");
        set.add("DAY_HOUR");
        set.add("DAY_MICROSECOND");
        set.add("DAY_MINUTE");
        set.add("DAY_SECOND");
        set.add("DEALLOCATE");
        set.add("DEC");
        set.add("DECIMAL");
        set.add("DECLARE");
        set.add("DEFAULT");
        set.add("DEFAULT_AUTH");
        set.add("DEFINER");
        set.add("DELAYED");
        set.add("DELAY_KEY_WRITE");
        set.add("DELETE");
        set.add("DESC");
        set.add("DESCRIBE");
        set.add("DES_KEY_FILE");
        set.add("DETERMINISTIC");
        set.add("DIAGNOSTICS");
        set.add("DIRECTORY");
        set.add("DISABLE");
        set.add("DISCARD");
        set.add("DISK");
        set.add("DISTINCT");
        set.add("DISTINCTROW");
        set.add("DIV");
        set.add("DO");
        set.add("DOUBLE");
        set.add("DROP");
        set.add("DUAL");
        set.add("DUMPFILE");
        set.add("DUPLICATE");
        set.add("DYNAMIC");
        set.add("EACH");
        set.add("ELSE");
        set.add("ELSEIF");
        set.add("ENABLE");
        set.add("ENCLOSED");
        set.add("ENCRYPTION");
        set.add("END");
        set.add("ENDS");
        set.add("ENGINE");
        set.add("ENGINES");
        set.add("ENUM");
        set.add("ERROR");
        set.add("ERRORS");
        set.add("ESCAPE");
        set.add("ESCAPED");
        set.add("EVENT");
        set.add("EVENTS");
        set.add("EVERY");
        set.add("EXCHANGE");
        set.add("EXECUTE");
        set.add("EXISTS");
        set.add("EXIT");
        set.add("EXPANSION");
        set.add("EXPIRE");
        set.add("EXPLAIN");
        set.add("EXPORT");
        set.add("EXTENDED");
        set.add("EXTENT_SIZE");
        set.add("FALSE");
        set.add("FAST");
        set.add("FAULTS");
        set.add("FETCH");
        set.add("FIELDS");
        set.add("FILE");
        set.add("FILE_BLOCK_SIZE");
        set.add("FILTER");
        set.add("FIRST");
        set.add("FIXED");
        set.add("FLOAT");
        set.add("FLOAT4");
        set.add("FLOAT8");
        set.add("FLUSH");
        set.add("FOLLOWS");
        set.add("FOR");
        set.add("FORCE");
        set.add("FOREIGN");
        set.add("FORMAT");
        set.add("FOUND");
        set.add("FROM");
        set.add("FULL");
        set.add("FULLTEXT");
        set.add("FUNCTION");
        set.add("GENERAL");
        set.add("GENERATED");
        set.add("GEOMETRY");
        set.add("GEOMETRYCOLLECTION");
        set.add("GET");
        set.add("GET_FORMAT");
        set.add("GLOBAL");
        set.add("GRANT");
        set.add("GRANTS");
        set.add("GROUP");
        set.add("GROUP_REPLICATION");
        set.add("HANDLER");
        set.add("HASH");
        set.add("HAVING");
        set.add("HELP");
        set.add("HIGH_PRIORITY");
        set.add("HOST");
        set.add("HOSTS");
        set.add("HOUR");
        set.add("HOUR_MICROSECOND");
        set.add("HOUR_MINUTE");
        set.add("HOUR_SECOND");
        set.add("IDENTIFIED");
        set.add("IF");
        set.add("IGNORE");
        set.add("IGNORE_SERVER_IDS");
        set.add("IMPORT");
        set.add("IN");
        set.add("INDEX");
        set.add("INDEXES");
        set.add("INFILE");
        set.add("INITIAL_SIZE");
        set.add("INNER");
        set.add("INOUT");
        set.add("INSENSITIVE");
        set.add("INSERT");
        set.add("INSERT_METHOD");
        set.add("INSTALL");
        set.add("INSTANCE");
        set.add("INT");
        set.add("INT1");
        set.add("INT2");
        set.add("INT3");
        set.add("INT4");
        set.add("INT8");
        set.add("INTEGER");
        set.add("INTERVAL");
        set.add("INTO");
        set.add("INVOKER");
        set.add("IO");
        set.add("IO_AFTER_GTIDS");
        set.add("IO_BEFORE_GTIDS");
        set.add("IO_THREAD");
        set.add("IPC");
        set.add("IS");
        set.add("ISOLATION");
        set.add("ISSUER");
        set.add("ITERATE");
        set.add("JOIN");
        set.add("JSON");
        set.add("KEY");
        set.add("KEYS");
        set.add("KEY_BLOCK_SIZE");
        set.add("KILL");
        set.add("LANGUAGE");
        set.add("LAST");
        set.add("LEADING");
        set.add("LEAVE");
        set.add("LEAVES");
        set.add("LEFT");
        set.add("LESS");
        set.add("LEVEL");
        set.add("LIKE");
        set.add("LIMIT");
        set.add("LINEAR");
        set.add("LINES");
        set.add("LINESTRING");
        set.add("LIST");
        set.add("LOAD");
        set.add("LOCAL");
        set.add("LOCALTIME");
        set.add("LOCALTIMESTAMP");
        set.add("LOCK");
        set.add("LOCKS");
        set.add("LOGFILE");
        set.add("LOGS");
        set.add("LONG");
        set.add("LONGBLOB");
        set.add("LONGTEXT");
        set.add("LOOP");
        set.add("LOW_PRIORITY");
        set.add("MASTER");
        set.add("MASTER_AUTO_POSITION");
        set.add("MASTER_BIND");
        set.add("MASTER_CONNECT_RETRY");
        set.add("MASTER_DELAY");
        set.add("MASTER_HEARTBEAT_PERIOD");
        set.add("MASTER_HOST");
        set.add("MASTER_LOG_FILE");
        set.add("MASTER_LOG_POS");
        set.add("MASTER_PASSWORD");
        set.add("MASTER_PORT");
        set.add("MASTER_RETRY_COUNT");
        set.add("MASTER_SERVER_ID");
        set.add("MASTER_SSL");
        set.add("MASTER_SSL_CA");
        set.add("MASTER_SSL_CAPATH");
        set.add("MASTER_SSL_CERT");
        set.add("MASTER_SSL_CIPHER");
        set.add("MASTER_SSL_CRL");
        set.add("MASTER_SSL_CRLPATH");
        set.add("MASTER_SSL_KEY");
        set.add("MASTER_SSL_VERIFY_SERVER_CERT");
        set.add("MASTER_TLS_VERSION");
        set.add("MASTER_USER");
        set.add("MATCH");
        set.add("MAXVALUE");
        set.add("MAX_CONNECTIONS_PER_HOUR");
        set.add("MAX_QUERIES_PER_HOUR");
        set.add("MAX_ROWS");
        set.add("MAX_SIZE");
        set.add("MAX_STATEMENT_TIME");
        set.add("MAX_UPDATES_PER_HOUR");
        set.add("MAX_USER_CONNECTIONS");
        set.add("MEDIUM");
        set.add("MEDIUMBLOB");
        set.add("MEDIUMINT");
        set.add("MEDIUMTEXT");
        set.add("MEMORY");
        set.add("MERGE");
        set.add("MESSAGE_TEXT");
        set.add("MICROSECOND");
        set.add("MIDDLEINT");
        set.add("MIGRATE");
        set.add("MINUTE");
        set.add("MINUTE_MICROSECOND");
        set.add("MINUTE_SECOND");
        set.add("MIN_ROWS");
        set.add("MOD");
        set.add("MODE");
        set.add("MODIFIES");
        set.add("MODIFY");
        set.add("MONTH");
        set.add("MULTILINESTRING");
        set.add("MULTIPOINT");
        set.add("MULTIPOLYGON");
        set.add("MUTEX");
        set.add("MYSQL_ERRNO");
        set.add("NAME");
        set.add("NAMES");
        set.add("NATIONAL");
        set.add("NATURAL");
        set.add("NCHAR");
        set.add("NDB");
        set.add("NDBCLUSTER");
        set.add("NEVER");
        set.add("NEW");
        set.add("NEXT");
        set.add("NO");
        set.add("NODEGROUP");
        set.add("NONBLOCKING");
        set.add("NONE");
        set.add("NOT");
        set.add("NO_WAIT");
        set.add("NO_WRITE_TO_BINLOG");
        set.add("NULL");
        set.add("NUMBER");
        set.add("NUMERIC");
        set.add("NVARCHAR");
        set.add("OFFSET");
        set.add("OLD_PASSWORD");
        set.add("ON");
        set.add("ONE");
        set.add("ONLY");
        set.add("OPEN");
        set.add("OPTIMIZE");
        set.add("OPTIMIZER_COSTS");
        set.add("OPTION");
        set.add("OPTIONALLY");
        set.add("OPTIONS");
        set.add("OR");
        set.add("ORDER");
        set.add("OUT");
        set.add("OUTER");
        set.add("OUTFILE");
        set.add("OWNER");
        set.add("PACK_KEYS");
        set.add("PAGE");
        set.add("PARSER");
        set.add("PARSE_GCOL_EXPR");
        set.add("PARTIAL");
        set.add("PARTITION");
        set.add("PARTITIONING");
        set.add("PARTITIONS");
        set.add("PASSWORD");
        set.add("PHASE");
        set.add("PLUGIN");
        set.add("PLUGINS");
        set.add("PLUGIN_DIR");
        set.add("POINT");
        set.add("POLYGON");
        set.add("PORT");
        set.add("PRECEDES");
        set.add("PRECISION");
        set.add("PREPARE");
        set.add("PRESERVE");
        set.add("PREV");
        set.add("PRIMARY");
        set.add("PRIVILEGES");
        set.add("PROCEDURE");
        set.add("PROCESSLIST");
        set.add("PROFILE");
        set.add("PROFILES");
        set.add("PROXY");
        set.add("PURGE");
        set.add("QUARTER");
        set.add("QUERY");
        set.add("QUICK");
        set.add("RANGE");
        set.add("READ");
        set.add("READS");
        set.add("READ_ONLY");
        set.add("READ_WRITE");
        set.add("REAL");
        set.add("REBUILD");
        set.add("RECOVER");
        set.add("REDOFILE");
        set.add("REDO_BUFFER_SIZE");
        set.add("REDUNDANT");
        set.add("REFERENCES");
        set.add("REGEXP");
        set.add("RELAY");
        set.add("RELAYLOG");
        set.add("RELAY_LOG_FILE");
        set.add("RELAY_LOG_POS");
        set.add("RELAY_THREAD");
        set.add("RELEASE");
        set.add("RELOAD");
        set.add("REMOVE");
        set.add("RENAME");
        set.add("REORGANIZE");
        set.add("REPAIR");
        set.add("REPEAT");
        set.add("REPEATABLE");
        set.add("REPLACE");
        set.add("REPLICATE_DO_DB");
        set.add("REPLICATE_DO_TABLE");
        set.add("REPLICATE_IGNORE_DB");
        set.add("REPLICATE_IGNORE_TABLE");
        set.add("REPLICATE_REWRITE_DB");
        set.add("REPLICATE_WILD_DO_TABLE");
        set.add("REPLICATE_WILD_IGNORE_TABLE");
        set.add("REPLICATION");
        set.add("REQUIRE");
        set.add("RESET");
        set.add("RESIGNAL");
        set.add("RESTORE");
        set.add("RESTRICT");
        set.add("RESUME");
        set.add("RETURN");
        set.add("RETURNED_SQLSTATE");
        set.add("RETURNS");
        set.add("REVERSE");
        set.add("REVOKE");
        set.add("RIGHT");
        set.add("RLIKE");
        set.add("ROLLBACK");
        set.add("ROLLUP");
        set.add("ROTATE");
        set.add("ROUTINE");
        set.add("ROW");
        set.add("ROWS");
        set.add("ROW_COUNT");
        set.add("ROW_FORMAT");
        set.add("RTREE");
        set.add("SAVEPOINT");
        set.add("SCHEDULE");
        set.add("SCHEMA");
        set.add("SCHEMAS");
        set.add("SCHEMA_NAME");
        set.add("SECOND");
        set.add("SECOND_MICROSECOND");
        set.add("SECURITY");
        set.add("SELECT");
        set.add("SENSITIVE");
        set.add("SEPARATOR");
        set.add("SERIAL");
        set.add("SERIALIZABLE");
        set.add("SERVER");
        set.add("SESSION");
        set.add("SET");
        set.add("SHARE");
        set.add("SHOW");
        set.add("SHUTDOWN");
        set.add("SIGNAL");
        set.add("SIGNED");
        set.add("SIMPLE");
        set.add("SLAVE");
        set.add("SLOW");
        set.add("SMALLINT");
        set.add("SNAPSHOT");
        set.add("SOCKET");
        set.add("SOME");
        set.add("SONAME");
        set.add("SOUNDS");
        set.add("SOURCE");
        set.add("SPATIAL");
        set.add("SPECIFIC");
        set.add("SQL");
        set.add("SQLEXCEPTION");
        set.add("SQLSTATE");
        set.add("SQLWARNING");
        set.add("SQL_AFTER_GTIDS");
        set.add("SQL_AFTER_MTS_GAPS");
        set.add("SQL_BEFORE_GTIDS");
        set.add("SQL_BIG_RESULT");
        set.add("SQL_BUFFER_RESULT");
        set.add("SQL_CACHE");
        set.add("SQL_CALC_FOUND_ROWS");
        set.add("SQL_NO_CACHE");
        set.add("SQL_SMALL_RESULT");
        set.add("SQL_THREAD");
        set.add("SQL_TSI_DAY");
        set.add("SQL_TSI_HOUR");
        set.add("SQL_TSI_MINUTE");
        set.add("SQL_TSI_MONTH");
        set.add("SQL_TSI_QUARTER");
        set.add("SQL_TSI_SECOND");
        set.add("SQL_TSI_WEEK");
        set.add("SQL_TSI_YEAR");
        set.add("SSL");
        set.add("STACKED");
        set.add("START");
        set.add("STARTING");
        set.add("STARTS");
        set.add("STATS_AUTO_RECALC");
        set.add("STATS_PERSISTENT");
        set.add("STATS_SAMPLE_PAGES");
        set.add("STATUS");
        set.add("STOP");
        set.add("STORAGE");
        set.add("STORED");
        set.add("STRAIGHT_JOIN");
        set.add("STRING");
        set.add("SUBCLASS_ORIGIN");
        set.add("SUBJECT");
        set.add("SUBPARTITION");
        set.add("SUBPARTITIONS");
        set.add("SUPER");
        set.add("SUSPEND");
        set.add("SWAPS");
        set.add("SWITCHES");
        set.add("TABLE");
        set.add("TABLES");
        set.add("TABLESPACE");
        set.add("TABLE_CHECKSUM");
        set.add("TABLE_NAME");
        set.add("TEMPORARY");
        set.add("TEMPTABLE");
        set.add("TERMINATED");
        set.add("TEXT");
        set.add("THAN");
        set.add("THEN");
        set.add("TIME");
        set.add("TIMESTAMP");
        set.add("TIMESTAMPADD");
        set.add("TIMESTAMPDIFF");
        set.add("TINYBLOB");
        set.add("TINYINT");
        set.add("TINYTEXT");
        set.add("TO");
        set.add("TRAILING");
        set.add("TRANSACTION");
        set.add("TRIGGER");
        set.add("TRIGGERS");
        set.add("TRUE");
        set.add("TRUNCATE");
        set.add("TYPE");
        set.add("TYPES");
        set.add("UNCOMMITTED");
        set.add("UNDEFINED");
        set.add("UNDO");
        set.add("UNDOFILE");
        set.add("UNDO_BUFFER_SIZE");
        set.add("UNICODE");
        set.add("UNINSTALL");
        set.add("UNION");
        set.add("UNIQUE");
        set.add("UNKNOWN");
        set.add("UNLOCK");
        set.add("UNSIGNED");
        set.add("UNTIL");
        set.add("UPDATE");
        set.add("UPGRADE");
        set.add("USAGE");
        set.add("USE");
        set.add("USER");
        set.add("USER_RESOURCES");
        set.add("USE_FRM");
        set.add("USING");
        set.add("UTC_DATE");
        set.add("UTC_TIME");
        set.add("UTC_TIMESTAMP");
        set.add("VALIDATION");
        set.add("VALUE");
        set.add("VALUES");
        set.add("VARBINARY");
        set.add("VARCHAR");
        set.add("VARCHARACTER");
        set.add("VARIABLES");
        set.add("VARYING");
        set.add("VIEW");
        set.add("VIRTUAL");
        set.add("WAIT");
        set.add("WARNINGS");
        set.add("WEEK");
        set.add("WEIGHT_STRING");
        set.add("WHEN");
        set.add("WHERE");
        set.add("WHILE");
        set.add("WITH");
        set.add("WITHOUT");
        set.add("WORK");
        set.add("WRAPPER");
        set.add("WRITE");
        set.add("X509");
        set.add("XA");
        set.add("XID");
        set.add("XML");
        set.add("XOR");
        set.add("YEAR");
        set.add("YEAR_MONTH");
        set.add("ZEROFIL");

        return set;
    }

    /// @return a modifiable set
    /// @see <a href="https://dev.mysql.com/doc/refman/8.2/en/keywords.html">Keywords and Reserved Words</a>
    static Set<String> create80KeywordsSet() {
        Set<String> set = create57KeywordsSet();

        set.add("ACTIVE");
        set.add("ADMIN");
        set.add("ARRAY");
        set.add("BUCKETS");
        set.add("CLONE");
        set.add("COMPONENT");
        set.add("CUME_DIST");
        set.add("DEFINITION");
        set.add("DENSE_RANK");
        set.add("DESCRIPTION");
        set.add("EMPTY");
        set.add("ENFORCED");
        set.add("EXCEPT");
        set.add("EXCLUDE");
        set.add("FAILED_LOGIN_ATTEMPTS");
        set.add("FIRST_VALUE");
        set.add("FOLLOWING");
        set.add("GEOMCOLLECTION");
        set.add("GET_MASTER_PUBLIC_KEY");
        set.add("GROUPING");
        set.add("GROUPS");
        set.add("HISTOGRAM");
        set.add("HISTORY");
        set.add("INACTIVE");
        set.add("INVISIBLE");
        set.add("JSON_TABLE");
        set.add("LAG");
        set.add("LAST_VALUE");
        set.add("LATERAL");
        set.add("LEAD");
        set.add("LOCKED");
        set.add("MASTER_COMPRESSION_ALGORITHMS");
        set.add("MASTER_PUBLIC_KEY_PATH");
        set.add("MASTER_TLS_CIPHERSUITES");
        set.add("MASTER_ZSTD_COMPRESSION_LEVEL");
        set.add("MEMBER");
        set.add("NESTED");
        set.add("NETWORK_NAMESPACE");
        set.add("NOWAIT");
        set.add("NTH_VALUE");
        set.add("NTILE");
        set.add("NULLS");
        set.add("OF");
        set.add("OFF");
        set.add("OJ");
        set.add("OLD");
        set.add("OPTIONAL");
        set.add("ORDINALITY");
        set.add("ORGANIZATION");
        set.add("OTHERS");
        set.add("OVER");
        set.add("PASSWORD_LOCK_TIME");
        set.add("PATH");
        set.add("PERCENT_RANK");
        set.add("PERSIST");
        set.add("PERSIST_ONLY");
        set.add("PRECEDING");
        set.add("PRIVILEGE_CHECKS_USER");
        set.add("PROCESS");
        set.add("RANDOM");
        set.add("RANK");
        set.add("RECURSIVE");
        set.add("REFERENCE");
        set.add("REQUIRE_ROW_FORMAT");
        set.add("RESOURCE");
        set.add("RESPECT");
        set.add("RESTART");
        set.add("RETAIN");
        set.add("REUSE");
        set.add("ROLE");
        set.add("ROW_NUMBER");
        set.add("SECONDARY");
        set.add("SECONDARY_ENGINE");
        set.add("SECONDARY_LOAD");
        set.add("SECONDARY_UNLOAD");
        set.add("SKIP");
        set.add("SRID");
        set.add("STREAM");
        set.add("SYSTEM");
        set.add("THREAD_PRIORITY");
        set.add("TIES");
        set.add("UNBOUNDED");
        set.add("VCPU");
        set.add("VISIBLE");
        set.add("WINDOW");

        // 8.0 removed keywords
        createMySQL80RemovedKeywords(set);
        return set;
    }


    /*################################## blow private method ##################################*/

    /// MySQL 8.0 Removed Keywords then Reserved Words
    ///
    /// @see <a href="https://dev.mysql.com/doc/refman/8.2/en/keywords.html">Keywords and Reserved Words</a>
    private static void createMySQL80RemovedKeywords(Set<String> keywords) {

        keywords.remove("ANALYSE");
        keywords.remove("DES_KEY_FILE");
        keywords.remove("PARSE_GCOL_EXPR");
        keywords.remove("REDOFILE");

        keywords.remove("SQL_CACHE");
    }

    /// @return an unmodifiable map
    /// @see <a href="https://dev.mysql.com/doc/refman/9.7/en/data-types.html">MySQL Data Types</a>
    private static Map<String, MySQLType> createAliasToTypeMap() {
        final MySQLType[] values = MySQLType.values();

        final Map<MySQLType, List<String>> listMap = _Collections.hashMapForSize(4 * 2);

        listMap.put(MySQLType.BOOLEAN, List.of("BOOLEAN", "BOOL"));
        listMap.put(MySQLType.INT, List.of("INT", "INTEGER"));
        listMap.put(MySQLType.INT_UNSIGNED, List.of("INT UNSIGNED", "INTEGER UNSIGNED"));
        listMap.put(MySQLType.DECIMAL, List.of("DECIMAL", "NUMERIC", "DEC"));

        listMap.put(MySQLType.DECIMAL_UNSIGNED, List.of("DECIMAL UNSIGNED", "NUMERIC UNSIGNED", "DEC UNSIGNED"));
        listMap.put(MySQLType.FLOAT, List.of("FLOAT", "FLOAT UNSIGNED", "REAL"));
        listMap.put(MySQLType.DOUBLE, List.of("DOUBLE", "DOUBLE UNSIGNED", "DOUBLE PRECISION", "DOUBLE PRECISION UNSIGNED"));
        listMap.put(MySQLType.DATETIME, List.of("DATETIME", "TIMESTAMP"));


        final Map<String, MySQLType> map = _Collections.hashMapForSize(values.length * 3);

        MySQLType type;
        for (Map.Entry<MySQLType, List<String>> e : listMap.entrySet()) {
            type = e.getKey();
            for (String alias : e.getValue()) {
                map.put(alias, type);
            }
        }

        for (MySQLType value : values) {
            map.put(value.typeName(), value);  // typeName be overridden
        }
        return Map.copyOf(map);
    }


}
