io.army.spring.ai.chat.memory.SpringAiChatMemory.id=io.army.generator.PostGeneratorStrategy
io.army.spring.ai.vectorstore.SpringAiVectorStore.embedding.Column.precision=1024
io.army.spring.ai.vectorstore.SpringAiVectorStore.IndexMeta[0].type=hnsw
io.army.spring.ai.vectorstore.SpringAiVectorStore.IndexMeta[0].field.embedding.opclass=vector_l2_ops
#
io.army.spring.ai.chat.memory.SpringAiChatMemory.batchNo.Column.name=batch_no
io.army.spring.ai.chat.memory.SpringAiChatMemory.userId.Mapping.value=io.army.mapping.SqlBigIntType
io.army.spring.ai.chat.memory.SpringAiChatMemory.userId.Column.defaultValue=0