#
io.army.example.coder.domain.CoderChatVectorStore.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779290105916}
io.army.example.coder.domain.CoderChatVectorStore.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.example.coder.domain.CoderChatVectorStore.embedding.Column.precision=1024
io.army.example.coder.domain.CoderChatVectorStore.conversationId.Mapping.value=io.army.mapping.SqlBigIntType
#
io.army.example.coder.domain.CoderDocumentVectorStore.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779290105918}
io.army.example.coder.domain.CoderDocumentVectorStore.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.example.coder.domain.CoderDocumentVectorStore.embedding.Column.precision=1024
#
io.army.example.coder.domain.CoderChatMemory.id.GeneratorStrategy=io.army.generator.Snowflake8GeneratorStrategy:{"startTime":1779103273327}
io.army.example.coder.domain.CoderChatMemory.id.Mapping.value=io.army.mapping.SqlBigIntType
io.army.example.coder.domain.CoderChatMemory.conversationId.Mapping.value=io.army.mapping.SqlBigIntType
#




